# configuration for master/CI branch
-
  branches:
    only:
      - master

  os: Visual Studio 2017
  configuration: Release
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '1.0.0.{build}'
    assembly_file_version: '1.0.0.{build}'
    assembly_informational_version: '1.0.0.{build}'
  build:
    project: AppVeyorDemo.sln
    verbosity: minimal
  after_build:
  - ps: nuget pack AppVeyorDemo.nuspec -Version $env:APPVEYOR_BUILD_VERSION
  artifacts:
  - path: '**\AppVeyorDemo.*.nupkg'

  version: 1.0.0-ci{build}
  nuget:
    account_feed: true
    project_feed: true
