# configuration for master/CI branch
-
  branches:
    only:
      - master
      
  os: Visual Studio 2017
  configuration: Release
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '1.0.0.{build}'
    assembly_file_version: '1.0.0.{build}'
    assembly_informational_version: '1.0.0.{build}'
  build:
    project: AppVeyorDemo.sln
    verbosity: minimal
  before_build: 
  - ps: >- 
      $version = "1.0.0-ci";
      $build = [int]::Parse($env:appveyor_build_number).ToString().PadLeft(4, '0');
      Update-AppveyorBuild -Version "$version$build";
  after_build:
  - ps: nuget pack AppVeyorDemo.nuspec -Version $env:APPVEYOR_BUILD_VERSION
  artifacts:
  - path: '**\AppVeyorDemo.*.nupkg'

  nuget:
    account_feed: true
    project_feed: true
