# configuration for master/CI branch
-
  branches:
    only:
      - master
      - ^(?:(\d+)\.)?(?:(\d+)\.)?(\*|\d+)$
  os: Visual Studio 2017
  configuration: Release
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '1.1.0.{build}'
    assembly_file_version: '1.1.0.{build}'
    assembly_informational_version: '1.0.0.{build}'
  build:
    project: AppVeyorDemo.sln
    verbosity: minimal
  before_build: 
  - ps: >- 
      if ($env:APPVEYOR_REPO_TAG -eq $TRUE) 
      { 
          Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }else{
          $version = "1.1.0-ci";
          $build = [int]::Parse($env:appveyor_build_number).ToString().PadLeft(4, '0');
          Update-AppveyorBuild -Version "$version$build";
      }
      
  after_build:
  - ps: nuget pack AppVeyorDemo.nuspec -Version $env:APPVEYOR_BUILD_VERSION
  artifacts:
  - path: '**\AppVeyorDemo.*.nupkg'

  nuget:
    account_feed: true
    project_feed: true
  deploy:
      - provider: NuGet
        server: https://www.myget.org/F/mohachouch/api/v2/package
        api_key:
          secure: O+1koezSt13pOeCKm7428lA1KFskCMzGG/+p80faYdQU6otzJCh0Q0jCx0nJU3bL
        on:
            appveyor_repo_tag: true     # deploy on tag push only
